services:
  - type: web
    name: instagram-webhook-poc
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: VERIFY_TOKEN
        generateValue: true
      - key: APP_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.7
    autoDeploy: true
